apiVersion: demo.k8soperator.com/v1alpha1
kind: HelloWorld
metadata:
  labels:
    app.kubernetes.io/name: k8soperator
    app.kubernetes.io/managed-by: kustomize
  name: helloworld-sample
spec:
  message: "Hey from your custom operator!"
